/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Components: typeof import('./components/index.vue')['default']
    copy: typeof import('./components/IndexComponent copy.vue')['default']
    FilmComponent: typeof import('./components/FilmComponent.vue')['default']
    FilmDetails: typeof import('./components/FilmDetailsComponent.vue')['default']
    FilmDetailsComponent: typeof import('./components/FilmDetailsComponent.vue')['default']
    FilmListComponent: typeof import('./components/FilmListComponent.vue')['default']
    FilmListComponetnt: typeof import('./comp./components/.vue']
    FilmPageComponent: typeof import('./components/FilmPageComponent.vue')['default']
    ForgotPassword: typeof import('./components/ForgotPassword.vue')['default']
    ForgotPasswordComponent: typeof import('./components/ForgotPasswordComponent.vue')['default']
    HeaderBar: typeof import('./components/PostHeaderBarComponent.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeComponent: typeof import('./components/HomeComponent.vue')['default']
    HomePage: typeof import('./components./components/MenuComponent.vue
    Index: typeof import('./components/IndexComponent.vue')['default']
    IndexComponent: typeof import('./components/IndexComponent.vue')['default']
    LateralMenuComponent: typeof import('./components/LateralMenuComponent.vue')['default']
    Login: typeof import('./components/LogInComponent.vue')['default']
    LogIn: typeof import('./components/LogInComponent.vue')['default']
    LogInComponent: typeof import('./components/LogInComponent.vue')['default']
    MenuComponent: typeof import('./components/PostHeaderBarComponent.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    PostHeaderBarComponent: typeof import('./components/PostHeaderBarComponent.vue')['default']
    PreferencesComponent: typeof import('./components/PreferencesComponent.vue')['default']
    PreHeaderBarComponent: typeof import('./components/PreHeaderBarComponent.vue')['default']
    ProfileComponent: typeof import('./components/ProfileComponent.vue')['default']
    ProfileCustomisation: typeof import('./components/UserCustomisationComponent.vue')['default']
    ProfileCustomisationComponent: typeof import('./components/UserCustomisationComponent.vue')['default']
    ReviewComponent: typeof import('./components/ReviewComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./components/SearchComponent.vue')['default']
    SignIn: typeof import('./components/SignUpComponent.vue')['default']
    SignIn2: typeof import('./components/SignIn2.vue')['default']
    SignInComponent: typeof import('./components/SignUpComponent.vue')['default']
    SignUpComponent: typeof import('./components/SignUpComponent.vue')['default']
    UserCustomisationComponent: typeof import('./components/UserCustomisationComponent.vue')['default']
  }
}
